"""Generate Amiberry ``.uae`` configuration files.

The goal is to produce a config that boots straight into a working Amiga for the
chosen model, with:

* the correct chipset / CPU / memory for the model,
* the maximum recommended Fast RAM,
* a real Kickstart ROM when available (otherwise the built-in AROS ROM),
* an optional floppy (ADF) inserted in DF0:,
* an optional mount of the floppycase ``games`` directory as a read/write hard
  drive (used for the bare "workbench" machine so WHDLoad games dropped there
  appear inside the Amiga).

WHDLoad games are *not* booted via this config: they are launched with
Amiberry's WHDLoad Booter (``--autoload``). The config is still written for
each game so it can carry launch metadata and show up as a tile.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from . import __version__
from .models import AmigaModel
from .paths import Paths
from .roms import AROS, DetectedRom

META_PREFIX = "; floppycase_"
#: Older EasyAmiga PoC configs used this prefix; still accepted when reading.
LEGACY_META_PREFIX = "; easyamiga_"
META_PREFIXES = (META_PREFIX, LEGACY_META_PREFIX)


@dataclass
class ConfigOptions:
    model: AmigaModel
    paths: Paths
    rom: DetectedRom | None = None  # None -> AROS built-in
    floppy: Path | None = None
    show_gui: bool = False  # False -> boot straight into emulation
    description: str | None = None
    #: Original game source (ADF/archive/folder) this config represents, if any.
    source: Path | None = None
    #: "adf" | "whdload" | None (None = bare machine, not a specific game).
    kind: str | None = None
    #: Mount the games/ directory as DH0:. Off for single-floppy game configs.
    mount_games: bool = True
    #: Directory Amiberry should scan for ROMs (defaults to paths.roms).
    roms_dir: Path | None = None


def _kickstart_lines(rom: DetectedRom | None) -> list[str]:
    if rom is None:
        # Built-in AROS Kickstart replacement (no real ROM required).
        return [
            "kickstart_rom_file=:AROS",
            "kickstart_rom_file_id=:AROS",
        ]
    lines = [f"kickstart_rom_file={rom.path}"]
    if rom.known:
        lines.append(f"kickstart_rom_file_id={rom.known.rom_id}")
    return lines


def _meta_lines(options: ConfigOptions) -> list[str]:
    return [
        f"{META_PREFIX}source={options.source if options.source else ''}",
        f"{META_PREFIX}kind={options.kind or ''}",
        f"{META_PREFIX}model={options.model.key}",
    ]


def render_config(options: ConfigOptions) -> str:
    model = options.model
    paths = options.paths
    rom = options.rom

    rom_desc = rom.description if rom else "AROS (built-in)"
    description = options.description or f"FloppyCase {model.name} ({rom_desc})"

    lines: list[str] = [
        f"; Generated by FloppyCase {__version__} - do not hand-edit unless you know UAE syntax",
        *_meta_lines(options),
        "config_version=8.1.0",
        f"config_description={description}",
        f"config_hardware=true",
        f"config_host=true",
        "",
        "; --- host ---",
        f"use_gui={'yes' if options.show_gui else 'no'}",
        "; Keep the game running even if its window loses focus.",
        "inactive_pause=false",
        "active_not_captured_pause=false",
        "",
        "; --- kickstart ---",
        f"rom_path={options.roms_dir or paths.roms}",
        *_kickstart_lines(rom),
        "",
        "; --- chipset ---",
        f"chipset={model.chipset}",
        f"chipset_compatible={model.chipset_compatible}",
        "",
        "; --- cpu ---",
        f"cpu_model={model.cpu_model}",
        f"cpu_speed={model.cpu_speed}",
        f"cpu_24bit_addressing={'true' if model.cpu_24bit else 'false'}",
        "",
        "; --- memory ---",
        f"chipmem_size={model.chipmem_size}",
        f"bogomem_size={model.bogomem_size}",
        f"fastmem_size={model.fastmem_mb}",
        "",
        "; --- floppy drives ---",
        "nr_floppies=1",
        f"floppy0={options.floppy if options.floppy else ''}",
        "floppy0type=0",
        "floppy_speed=800",
        "",
    ]

    if options.mount_games:
        lines += [
            "; --- hard drives ---",
            "; Mount the FloppyCase games directory read/write as DH0:Games.",
            "; bootpri=-128 keeps it from ever taking over the boot sequence.",
            f"filesystem2=rw,DH0:Games:{paths.games},-128",
            f"uaehf0=dir,rw,DH0:Games:{paths.games},-128",
            "",
        ]

    return "\n".join(lines)


def write_config(options: ConfigOptions, name: str) -> Path:
    """Render and write a config file into the configs directory. Returns the path."""
    options.paths.configs.mkdir(parents=True, exist_ok=True)
    target = options.paths.config_file(name)
    target.write_text(render_config(options), encoding="utf-8")
    return target


def read_meta(config_path: Path) -> dict[str, str]:
    """Read ``; floppycase_*`` (or legacy ``; easyamiga_*``) config metadata."""
    meta: dict[str, str] = {}
    try:
        for line in config_path.read_text(encoding="utf-8").splitlines():
            for prefix in META_PREFIXES:
                if line.startswith(prefix):
                    key, _, value = line[len(prefix) :].partition("=")
                    meta[key.strip()] = value.strip()
                    break
    except OSError:
        pass
    return meta
