"""Generate Amiberry ``.uae`` configuration files.

The goal is to produce a config that boots straight into a working Amiga for the
chosen model, with:

* the correct chipset / CPU / memory for the model,
* the maximum recommended Fast RAM,
* a real Kickstart ROM when available (otherwise the built-in AROS ROM),
* the easyamiga ``games`` directory mounted as a read/write hard drive so WHDLoad
  games dropped there appear inside the Amiga,
* an optional floppy (ADF) inserted in DF0:.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from . import __version__
from .models import AmigaModel
from .paths import Paths
from .roms import AROS, DetectedRom


@dataclass
class ConfigOptions:
    model: AmigaModel
    paths: Paths
    rom: DetectedRom | None = None  # None -> AROS built-in
    floppy: Path | None = None
    show_gui: bool = False  # False -> boot straight into emulation
    description: str | None = None


def _kickstart_lines(rom: DetectedRom | None) -> list[str]:
    if rom is None:
        # Built-in AROS Kickstart replacement (no real ROM required).
        return [
            "kickstart_rom_file=:AROS",
            "kickstart_rom_file_id=:AROS",
        ]
    lines = [f"kickstart_rom_file={rom.path}"]
    if rom.known:
        lines.append(f"kickstart_rom_file_id={rom.known.rom_id}")
    return lines


def render_config(options: ConfigOptions) -> str:
    model = options.model
    paths = options.paths
    rom = options.rom

    rom_desc = rom.description if rom else "AROS (built-in)"
    description = options.description or f"easyamiga {model.name} ({rom_desc})"

    lines: list[str] = [
        f"; Generated by easyamiga {__version__} - do not hand-edit unless you know UAE syntax",
        "config_version=8.1.0",
        f"config_description={description}",
        f"config_hardware=true",
        f"config_host=true",
        "",
        "; --- host ---",
        f"use_gui={'yes' if options.show_gui else 'no'}",
        "; Keep the game running even if its window loses focus.",
        "inactive_pause=false",
        "active_not_captured_pause=false",
        "",
        "; --- kickstart ---",
        f"rom_path={paths.roms}",
        *_kickstart_lines(rom),
        "",
        "; --- chipset ---",
        f"chipset={model.chipset}",
        f"chipset_compatible={model.chipset_compatible}",
        "",
        "; --- cpu ---",
        f"cpu_model={model.cpu_model}",
        f"cpu_speed={model.cpu_speed}",
        f"cpu_24bit_addressing={'true' if model.cpu_24bit else 'false'}",
        "",
        "; --- memory ---",
        f"chipmem_size={model.chipmem_size}",
        f"bogomem_size={model.bogomem_size}",
        f"fastmem_size={model.fastmem_mb}",
        "",
        "; --- floppy drives ---",
        "nr_floppies=1",
        f"floppy0={options.floppy if options.floppy else ''}",
        "floppy0type=0",
        "floppy_speed=800",
        "",
        "; --- hard drives ---",
        "; Mount the easyamiga games directory read/write as DH0:Games.",
        "; bootpri=-10 keeps it from taking over the boot sequence.",
        f"filesystem2=rw,DH0:Games:{paths.games},-10",
        f"uaehf0=dir,rw,DH0:Games:{paths.games},-10",
        "",
    ]
    return "\n".join(lines)


def write_config(options: ConfigOptions, name: str) -> Path:
    """Render and write a config file into the configs directory. Returns the path."""
    options.paths.configs.mkdir(parents=True, exist_ok=True)
    target = options.paths.config_file(name)
    target.write_text(render_config(options), encoding="utf-8")
    return target
